In [70]:
import pandas as pd
import matplotlib.pyplot as plot

In [71]:
csvDir = "alt_fuel_stations (Jan 9 2021).csv"

originaldf = pd.read_csv(csvDir, encoding="ISO-8859-1")
originaldf

C:\Users\sanab\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (6,20) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,...,EV Pricing,EV Pricing (French),LPG Nozzle Types,Hydrogen Pressures,Hydrogen Standards,CNG Fill Type Code,CNG PSI,CNG Vehicle Class,LNG Vehicle Class,EV On-Site Renewable Source
0,ELEC,Los Angeles Convention Center,1201 S Figueroa St,West hall and South hall,Los Angeles,CA,90015,NaN,213-741-1151,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ELEC,California Air Resources Board,9530 Telstar Ave,NaN,El Monte,CA,91731,NaN,626-575-6800,E,...,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ELEC,Scripps Green Hospital,10666 N Torrey Pines Rd,"Patient Parking Structure, level G",La Jolla,CA,92037,NaN,858-554-9100,E,...,Pay to Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ELEC,San Diego Wild Animal Park,15500 San Pasqual Valley Rd,NaN,Escondido,CA,92027,NaN,760-747-8702,E,...,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ELEC,Galpin Motors,15421 Roscoe Blvd,NaN,Sepulveda,CA,91343,NaN,800-256-6219,E,...,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28981,ELEC,LEVEL 1 GARAGE,SE 12th &amp; Stark,NaN,Portland,OR,97214,NaN,888-758-4389,E,...,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28982,ELEC,CHESTNUT COMMON,180 Friendship St,NaN,Providence,RI,02903,NaN,888-758-4389,E,...,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28983,ELEC,METRO NASHVILLE,2060 15th Ave,NaN,Nashville,TN,37212,NaN,888-758-4389,E,...,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28984,ELEC,BGE-Howard Community College,10901 Little Patuxent Pkwy,NaN,Columbia,MD,21044,NaN,855-900-7584,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28985,ELEC,BGE-Essex Park and Ride,23 Eastern Blvd,NaN,Essex,MD,21221,NaN,855-900-7584,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
# Begin dataset review

print(f'No. of columns: {len(originaldf.columns)}')
print(f'No. of rows: {len(originaldf)}')
print(originaldf.dtypes)

No. of columns: 64
No. of rows: 28986
Fuel Type Code                  object
Station Name                    object
Street Address                  object
Intersection Directions         object
City                            object
                                ...
CNG Fill Type Code             float64
CNG PSI                        float64
CNG Vehicle Class              float64
LNG Vehicle Class              float64
EV On-Site Renewable Source     object
Length: 64, dtype: object

In [123]:
# Visually review content of each series

originaldf.iloc[:,0:7].head(10)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP
0,ELEC,Los Angeles Convention Center,1201 S Figueroa St,West hall and South hall,Los Angeles,CA,90015
1,ELEC,California Air Resources Board,9530 Telstar Ave,NaN,El Monte,CA,91731
2,ELEC,Scripps Green Hospital,10666 N Torrey Pines Rd,"Patient Parking Structure, level G",La Jolla,CA,92037
3,ELEC,San Diego Wild Animal Park,15500 San Pasqual Valley Rd,NaN,Escondido,CA,92027
4,ELEC,Galpin Motors,15421 Roscoe Blvd,NaN,Sepulveda,CA,91343
5,ELEC,Galleria at Tyler,1299 Galleria at Tyler,NaN,Riverside,CA,92503
6,ELEC,City of Pasadena - Holly Street Garage,150 E Holly St,NaN,Pasadena,CA,91103
7,ELEC,City of Pasadena - De Lacey Garage,45 De Lacey Ave,NaN,Pasadena,CA,91105
8,ELEC,City of Pasadena - Schoolhouse Garage,33 E Green St,NaN,Pasadena,CA,91105
9,ELEC,Pasadena Hilton,150 S Los Robles,Located at valet and self parking,Pasadena,CA,91101

In [124]:
# Visually review content of each series
originaldf.iloc[:,8:15].head(10)

,Station Phone,Status Code,Expected Date,Groups With Access Code,Access Days Time,Cards Accepted,BD Blends
0,213-741-1151,E,NaN,Public,24 hours daily; pay lot,NaN,NaN
1,626-575-6800,E,NaN,Public,24 hours daily,NaN,NaN
2,858-554-9100,E,NaN,Public,24 hours daily,NaN,NaN
3,760-747-8702,E,NaN,Public,24 hours daily,NaN,NaN
4,800-256-6219,E,NaN,Public - Call ahead,Dealership business hours,NaN,NaN
5,951-351-3110,E,NaN,Public,6am-12am daily,NaN,NaN
6,626-744-7665,E,NaN,Public,24 hours daily; pay lot,NaN,NaN
7,626-744-7665,E,NaN,Public,24 hours daily; pay lot,NaN,NaN
8,626-744-7665,E,NaN,Public,24 hours daily; pay lot,NaN,NaN
9,626-577-1000,E,NaN,Public,24 hours daily; for guest use only; valet fee,NaN,NaN

In [125]:
# Visually review content of each series
originaldf.iloc[:,16:23].head(10)

,NG PSI,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,EV Other Info,EV Network,EV Network Web
0,NaN,NaN,12.0,NaN,NaN,Non-Networked,NaN
1,NaN,NaN,3.0,NaN,NaN,Non-Networked,NaN
2,NaN,NaN,1.0,NaN,NaN,Non-Networked,NaN
3,NaN,NaN,2.0,NaN,NaN,Non-Networked,NaN
4,NaN,NaN,2.0,NaN,NaN,Non-Networked,NaN
5,NaN,NaN,4.0,NaN,NaN,Non-Networked,NaN
6,NaN,NaN,16.0,NaN,NaN,Non-Networked,NaN
7,NaN,NaN,2.0,NaN,NaN,Non-Networked,NaN
8,NaN,NaN,3.0,NaN,NaN,Non-Networked,NaN
9,NaN,NaN,4.0,NaN,NaN,Non-Networked,NaN

In [126]:
originaldf.iloc[:,24:31].head(10)

,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Owner Type Code,Federal Agency ID
0,34.040539,-118.271387,2020-11-09,1523,2020-11-09 16:53:32 UTC,P,NaN
1,34.068720,-118.064000,2019-09-09,1583,2020-12-09 23:35:08 UTC,SG,NaN
2,32.899470,-117.243000,2019-12-12,6355,2020-12-06 18:51:53 UTC,P,NaN
3,33.098589,-117.004433,2019-02-06,6384,2020-12-31 00:28:50 UTC,P,NaN
4,34.221665,-118.468371,2019-05-09,6405,2021-01-07 15:47:22 UTC,P,NaN
5,33.909914,-117.459053,2020-02-06,6425,2020-02-06 21:24:11 UTC,P,NaN
6,34.147620,-118.147111,2020-04-08,6505,2020-04-08 12:29:55 UTC,LG,NaN
7,34.145138,-118.152655,2020-12-03,6506,2020-12-03 22:33:12 UTC,LG,NaN
8,34.145119,-118.150133,2020-12-03,6507,2020-12-03 22:33:12 UTC,LG,NaN
9,34.142973,-118.140553,2020-08-05,6508,2020-08-05 19:05:18 UTC,P,NaN

In [127]:
originaldf.iloc[:,32:39].head(10)

,Open Date,Hydrogen Status Link,NG Vehicle Class,LPG Primary,E85 Blender Pump,EV Connector Types,Country
0,1995-08-30,NaN,NaN,NaN,NaN,J1772,US
1,1996-10-15,NaN,NaN,NaN,NaN,J1772,US
2,1997-07-30,NaN,NaN,NaN,NaN,J1772,US
3,2014-09-02,NaN,NaN,NaN,NaN,J1772,US
4,2012-12-11,NaN,NaN,NaN,NaN,J1772,US
5,1997-08-30,NaN,NaN,NaN,NaN,J1772,US
6,1997-08-30,NaN,NaN,NaN,NaN,J1772,US
7,1997-08-30,NaN,NaN,NaN,NaN,J1772,US
8,1997-08-30,NaN,NaN,NaN,NaN,J1772,US
9,1997-08-31,NaN,NaN,NaN,NaN,J1772,US

In [128]:
originaldf.iloc[:,40:47].head(10)

,Access Days Time (French),BD Blends (French),Groups With Access Code (French),Hydrogen Is Retail,Access Code,Access Detail Code,Federal Agency Code
0,NaN,NaN,Public,NaN,public,NaN,NaN
1,NaN,NaN,Public,NaN,public,NaN,NaN
2,NaN,NaN,Public,NaN,public,NaN,NaN
3,NaN,NaN,Public,NaN,public,NaN,NaN
4,NaN,NaN,Public - Appeler Ã l'avance,NaN,public,CALL,NaN
5,NaN,NaN,Public,NaN,public,NaN,NaN
6,NaN,NaN,Public,NaN,public,NaN,NaN
7,NaN,NaN,Public,NaN,public,NaN,NaN
8,NaN,NaN,Public,NaN,public,NaN,NaN
9,NaN,NaN,Public,NaN,public,NaN,NaN

In [129]:
originaldf.iloc[:,48:55].head(10)

,CNG Dispenser Num,CNG On-Site Renewable Source,CNG Total Compression Capacity,CNG Storage Capacity,LNG On-Site Renewable Source,E85 Other Ethanol Blends,EV Pricing
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,Free
2,NaN,NaN,NaN,NaN,NaN,NaN,Pay to Park
3,NaN,NaN,NaN,NaN,NaN,NaN,Free
4,NaN,NaN,NaN,NaN,NaN,NaN,Free
5,NaN,NaN,NaN,NaN,NaN,NaN,Free
6,NaN,NaN,NaN,NaN,NaN,NaN,Free
7,NaN,NaN,NaN,NaN,NaN,NaN,Free
8,NaN,NaN,NaN,NaN,NaN,NaN,Free
9,NaN,NaN,NaN,NaN,NaN,NaN,Free

In [131]:
originaldf.iloc[:,56:65].head(10)

,LPG Nozzle Types,Hydrogen Pressures,Hydrogen Standards,CNG Fill Type Code,CNG PSI,CNG Vehicle Class,LNG Vehicle Class,EV On-Site Renewable Source
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
originaldf.columns

# Show percentage of NaN values
# Setup removal recommendation list
removeSeries = []

for x in range (len(originaldf.columns)):
    if (1 - (originaldf.iloc[:,x].count())/(len(originaldf))) > 0.7:
        print(f'Percentage of NaN values in series "{originaldf.iloc[:,x].name}": {1 - ((originaldf.iloc[:,x].count())/(len(originaldf)))}')
        removeSeries.append(originaldf.iloc[:,x].name)

Percentage of NaN values in series "Plus4": 1.0
Percentage of NaN values in series "Expected Date": 0.9987235217001311
Percentage of NaN values in series "Cards Accepted": 0.9816118125991858
Percentage of NaN values in series "BD Blends": 1.0
Percentage of NaN values in series "NG Fill Type Code": 1.0
Percentage of NaN values in series "NG PSI": 1.0
Percentage of NaN values in series "EV Level1 EVSE Num": 0.9800593389912371
Percentage of NaN values in series "EV DC Fast Count": 0.8506175395018285
Percentage of NaN values in series "EV Other Info": 0.998896018767681
Percentage of NaN values in series "Federal Agency ID": 0.998861519354171
Percentage of NaN values in series "Federal Agency Name": 0.998861519354171
Percentage of NaN values in series "Hydrogen Status Link": 1.0
Percentage of NaN values in series "NG Vehicle Class": 1.0
Percentage of NaN values in series "LPG Primary": 1.0
Percentage of NaN values in series "E85 Blender Pump": 1.0
Percentage of NaN values in series "Intersection Directions (French)": 1.0
Percentage of NaN values in series "Access Days Time (French)": 1.0
Percentage of NaN values in series "BD Blends (French)": 1.0
Percentage of NaN values in series "Hydrogen Is Retail": 1.0
Percentage of NaN values in series "Access Detail Code": 0.905747602290761
Percentage of NaN values in series "Federal Agency Code": 0.998861519354171
Percentage of NaN values in series "CNG Dispenser Num": 1.0
Percentage of NaN values in series "CNG On-Site Renewable Source": 1.0
Percentage of NaN values in series "CNG Total Compression Capacity": 1.0
Percentage of NaN values in series "CNG Storage Capacity": 1.0
Percentage of NaN values in series "LNG On-Site Renewable Source": 1.0
Percentage of NaN values in series "E85 Other Ethanol Blends": 1.0
Percentage of NaN values in series "EV Pricing (French)": 1.0
Percentage of NaN values in series "LPG Nozzle Types": 1.0
Percentage of NaN values in series "Hydrogen Pressures": 1.0
Percentage of NaN values in series "Hydrogen Standards": 1.0
Percentage of NaN values in series "CNG Fill Type Code": 1.0
Percentage of NaN values in series "CNG PSI": 1.0
Percentage of NaN values in series "CNG Vehicle Class": 1.0
Percentage of NaN values in series "LNG Vehicle Class": 1.0
Percentage of NaN values in series "EV On-Site Renewable Source": 0.9937901055682054

In [99]:
removeSeries

['Plus4',
 'Expected Date',
 'Cards Accepted',
 'BD Blends',
 'NG Fill Type Code',
 'NG PSI',
 'EV Level1 EVSE Num',
 'EV DC Fast Count',
 'EV Other Info',
 'Federal Agency ID',
 'Federal Agency Name',
 'Hydrogen Status Link',
 'NG Vehicle Class',
 'LPG Primary',
 'E85 Blender Pump',
 'Intersection Directions (French)',
 'Access Days Time (French)',
 'BD Blends (French)',
 'Hydrogen Is Retail',
 'Access Detail Code',
 'Federal Agency Code',
 'CNG Dispenser Num',
 'CNG On-Site Renewable Source',
 'CNG Total Compression Capacity',
 'CNG Storage Capacity',
 'LNG On-Site Renewable Source',
 'E85 Other Ethanol Blends',
 'EV Pricing (French)',
 'LPG Nozzle Types',
 'Hydrogen Pressures',
 'Hydrogen Standards',
 'CNG Fill Type Code',
 'CNG PSI',
 'CNG Vehicle Class',
 'LNG Vehicle Class',
 'EV On-Site Renewable Source']

In [100]:
# Remove the rows with excessive NaN values

colremoved = originaldf.drop(removeSeries, axis = 1)
colremoved.head(3)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Station Phone,Status Code,Groups With Access Code,...,ID,Updated At,Owner Type Code,Open Date,EV Connector Types,Country,Groups With Access Code (French),Access Code,Facility Type,EV Pricing
0,ELEC,Los Angeles Convention Center,1201 S Figueroa St,West hall and South hall,Los Angeles,CA,90015,213-741-1151,E,Public,...,1523,2020-11-09 16:53:32 UTC,P,1995-08-30,J1772,US,Public,public,PARKING_GARAGE,NaN
1,ELEC,California Air Resources Board,9530 Telstar Ave,NaN,El Monte,CA,91731,626-575-6800,E,Public,...,1583,2020-12-09 23:35:08 UTC,SG,1996-10-15,J1772,US,Public,public,STATE_GOV,Free
2,ELEC,Scripps Green Hospital,10666 N Torrey Pines Rd,"Patient Parking Structure, level G",La Jolla,CA,92037,858-554-9100,E,Public,...,6355,2020-12-06 18:51:53 UTC,P,1997-07-30,J1772,US,Public,public,HOSPITAL,Pay to Park

In [106]:
# Ensure only electric, non-hydrogen stations are provided 

altStationsClean = colremoved.loc[colremoved["Fuel Type Code"] == "ELEC",:]
altStationsClean

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Station Phone,Status Code,Groups With Access Code,...,ID,Updated At,Owner Type Code,Open Date,EV Connector Types,Country,Groups With Access Code (French),Access Code,Facility Type,EV Pricing
0,ELEC,Los Angeles Convention Center,1201 S Figueroa St,West hall and South hall,Los Angeles,CA,90015,213-741-1151,E,Public,...,1523,2020-11-09 16:53:32 UTC,P,1995-08-30,J1772,US,Public,public,PARKING_GARAGE,NaN
1,ELEC,California Air Resources Board,9530 Telstar Ave,NaN,El Monte,CA,91731,626-575-6800,E,Public,...,1583,2020-12-09 23:35:08 UTC,SG,1996-10-15,J1772,US,Public,public,STATE_GOV,Free
2,ELEC,Scripps Green Hospital,10666 N Torrey Pines Rd,"Patient Parking Structure, level G",La Jolla,CA,92037,858-554-9100,E,Public,...,6355,2020-12-06 18:51:53 UTC,P,1997-07-30,J1772,US,Public,public,HOSPITAL,Pay to Park
3,ELEC,San Diego Wild Animal Park,15500 San Pasqual Valley Rd,NaN,Escondido,CA,92027,760-747-8702,E,Public,...,6384,2020-12-31 00:28:50 UTC,P,2014-09-02,J1772,US,Public,public,PAY_LOT,Free
4,ELEC,Galpin Motors,15421 Roscoe Blvd,NaN,Sepulveda,CA,91343,800-256-6219,E,Public - Call ahead,...,6405,2021-01-07 15:47:22 UTC,P,2012-12-11,J1772,US,Public - Appeler Ã l'avance,public,CAR_DEALER,Free
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28981,ELEC,LEVEL 1 GARAGE,SE 12th &amp; Stark,NaN,Portland,OR,97214,888-758-4389,E,Public,...,171220,2021-01-09 00:27:45 UTC,NaN,NaN,J1772,US,Public,public,NaN,Free
28982,ELEC,CHESTNUT COMMON,180 Friendship St,NaN,Providence,RI,02903,888-758-4389,E,Public,...,171221,2021-01-09 00:27:45 UTC,NaN,NaN,J1772,US,Public,public,NaN,Free
28983,ELEC,METRO NASHVILLE,2060 15th Ave,NaN,Nashville,TN,37212,888-758-4389,E,Public,...,171222,2021-01-09 00:27:45 UTC,NaN,NaN,J1772,US,Public,public,NaN,Free
28984,ELEC,BGE-Howard Community College,10901 Little Patuxent Pkwy,NaN,Columbia,MD,21044,855-900-7584,E,Public,...,171223,2021-01-09 01:35:32 UTC,NaN,NaN,CHADEMO J1772 J1772COMBO,US,Public,public,NaN,NaN
28985,ELEC,BGE-Essex Park and Ride,23 Eastern Blvd,NaN,Essex,MD,21221,855-900-7584,E,Public,...,171224,2021-01-09 01:35:32 UTC,NaN,NaN,J1772,US,Public,public,NaN,NaN

In [102]:
altStationsClean.to_csv("alt_fuel_stations_cleaned.csv", index = False , header = True)

In [103]:
csvDir = "alt_fuel_stations_cleaned.csv"

altStationdf = pd.read_csv(csvDir, encoding="ISO-8859-1")
altStationdf.head(3)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Station Phone,Status Code,Groups With Access Code,...,ID,Updated At,Owner Type Code,Open Date,EV Connector Types,Country,Groups With Access Code (French),Access Code,Facility Type,EV Pricing
0,ELEC,Los Angeles Convention Center,1201 S Figueroa St,West hall and South hall,Los Angeles,CA,90015,213-741-1151,E,Public,...,1523,2020-11-09 16:53:32 UTC,P,1995-08-30,J1772,US,Public,public,PARKING_GARAGE,NaN
1,ELEC,California Air Resources Board,9530 Telstar Ave,NaN,El Monte,CA,91731,626-575-6800,E,Public,...,1583,2020-12-09 23:35:08 UTC,SG,1996-10-15,J1772,US,Public,public,STATE_GOV,Free
2,ELEC,Scripps Green Hospital,10666 N Torrey Pines Rd,"Patient Parking Structure, level G",La Jolla,CA,92037,858-554-9100,E,Public,...,6355,2020-12-06 18:51:53 UTC,P,1997-07-30,J1772,US,Public,public,HOSPITAL,Pay to Park

In [104]:
stationsGrouped = altStationdf.groupby("City")
stationCities = stationsGrouped.count()
stationCities.loc["Los Angeles","Fuel Type Code"]

759